"""
Script to populate the database with famous paintings and their embeddings.
Run this script to initialize the database with sample data.

Usage: python populate_paintings.py
"""

import sys
from sqlalchemy import text
from database import SessionLocal
from recsys.utils import get_text_embedding

# 100+ Famous paintings across different styles
PAINTINGS = [
    # Abstract
    {"title": "Composition VIII", "artist": "Wassily Kandinsky", "style": "abstract", "image_url": "https://www.guggenheim.org/wp-content/uploads/1923/01/37.262_ph_web-1.jpg", "description": "Vibrant abstract composition featuring geometric shapes including circles, triangles, and lines in bold primary colors of red, yellow, blue, and black against a light beige background with dynamic angular forms and intersecting planes"},
    {"title": "Broadway Boogie Woogie", "artist": "Piet Mondrian", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Piet_Mondriaan%2C_1942_-_Broadway_Boogie_Woogie.jpg/800px-Piet_Mondriaan%2C_1942_-_Broadway_Boogie_Woogie.jpg", "description": "Geometric grid pattern with bright yellow, red, and blue rectangular blocks creating a rhythmic visual pattern resembling city streets from above, featuring a white background with colorful squares arranged in a syncopated grid"},
    {"title": "No. 5, 1948", "artist": "Jackson Pollock", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Pollock-Krasner_House_-_2010-08-14_-_IMG_1571.JPG/600px-Pollock-Krasner_House_-_2010-08-14_-_IMG_1571.JPG", "description": "Chaotic abstract expressionist drip painting with dense layers of brown, yellow, gray, and white paint splattered across the canvas creating an intricate web-like texture with no recognizable forms"},
    {"title": "Black Square", "artist": "Kazimir Malevich", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Black_Square.jpg/600px-Black_Square.jpg", "description": "Minimalist suprematist painting featuring a solid black square centered on a white background representing pure geometric abstraction and the elimination of representational art"},
    {"title": "Suprematist Composition", "artist": "Kazimir Malevich", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Suprematist_Composition_-_Kazimir_Malevich.jpg/600px-Suprematist_Composition_-_Kazimir_Malevich.jpg", "description": "Dynamic geometric composition with colored rectangles, squares, and diagonal lines in red, yellow, blue, black, and white floating against a pale background creating spatial tension"},
    {"title": "Improvisation 28", "artist": "Wassily Kandinsky", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Vassily_Kandinsky%2C_1912_-_Improvisation_28_%28zweite_Fassung%29.jpg/800px-Vassily_Kandinsky%2C_1912_-_Improvisation_28_%28zweite_Fassung%29.jpg", "description": "Vibrant abstract landscape with swirling forms and bold colors including yellow, orange, blue, and black with hints of architectural and organic shapes dissolving into pure abstraction"},
    {"title": "Orange, Red, Yellow", "artist": "Mark Rothko", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Mark_Rothko%2C_Untitled_%28Violet%2C_Black%2C_Orange%2C_Yellow_on_White_and_Red%29%2C_1949%2C_Solomon_R._Guggenheim_Museum%2C_New_York.jpg/600px-Mark_Rothko%2C_Untitled_%28Violet%2C_Black%2C_Orange%2C_Yellow_on_White_and_Red%29%2C_1949%2C_Solomon_R._Guggenheim_Museum%2C_New_York.jpg", "description": "Color field painting with horizontal bands of warm colors including orange, red, and yellow with soft blurred edges creating a meditative atmospheric effect and luminous quality"},
    {"title": "Woman I", "artist": "Willem de Kooning", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/De_Kooning%2C_Willem_-_Woman_V_%281952-53%29.jpg/600px-De_Kooning%2C_Willem_-_Woman_V_%281952-53%29.jpg", "description": "Abstract expressionist female figure with aggressive brushstrokes in flesh tones, yellows, and blues creating a distorted semi-abstract woman with exaggerated features and gestural energy"},
    {"title": "Blue Poles", "artist": "Jackson Pollock", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Blue_Poles.png/800px-Blue_Poles.png", "description": "Large-scale abstract expressionist painting with chaotic drips and splatters in black, white, yellow, and orange with eight vertical blue poles cutting through the composition"},
    {"title": "Untitled (Yellow and Blue)", "artist": "Mark Rothko", "style": "abstract", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Mark_Rothko%2C_No._61_%28Rust_and_Blue%29.jpg/600px-Mark_Rothko%2C_No._61_%28Rust_and_Blue%29.jpg", "description": "Color field painting with large rectangular blocks of deep rust orange and dark blue stacked horizontally with soft diffused edges creating emotional depth and contemplative mood"},
    
    # Realism
    {"title": "The Gleaners", "artist": "Jean-François Millet", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jean-François_Millet_-_Gleaners_-_Google_Art_Project_2.jpg/800px-Jean-François_Millet_-_Gleaners_-_Google_Art_Project.jpg", "description": "Rural landscape scene depicting three peasant women bent over gathering leftover grain in a golden wheat field under a soft blue sky with warm earth tones and muted colors representing agricultural labor"},
    {"title": "The Stone Breakers", "artist": "Gustave Courbet", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Gustave_Courbet_-_The_Stone_Breakers_-_WGA05457.jpg/800px-Gustave_Courbet_-_The_Stone_Breakers_-_WGA05457.jpg", "description": "Somber outdoor scene showing two manual laborers breaking stones on a roadside with brown, gray, and earth tones portraying working-class hardship in a naturalistic style"},
    {"title": "The Gross Clinic", "artist": "Thomas Eakins", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/The_Gross_Clinic.jpg/600px-The_Gross_Clinic.jpg", "description": "Dramatic medical theater interior with surgeons performing an operation under bright light, featuring dark browns and blacks with dramatic chiaroscuro highlighting the clinical procedure and observing students"},
    {"title": "Barge Haulers on the Volga", "artist": "Ilya Repin", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Ilya_Repin_-_Barge_Haulers_on_the_Volga_-_Google_Art_Project.jpg/800px-Ilya_Repin_-_Barge_Haulers_on_the_Volga_-_Google_Art_Project.jpg", "description": "River landscape showing eleven laborers straining to pull a barge along the sandy shore under a pale blue sky, painted in naturalistic browns, grays, and blues depicting harsh physical labor"},
    {"title": "A Burial At Ornans", "artist": "Gustave Courbet", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Gustave_Courbet_-_A_Burial_at_Ornans_-_Google_Art_Project_2.jpg/800px-Gustave_Courbet_-_A_Burial_at_Ornans_-_Google_Art_Project_2.jpg", "description": "Large-scale funeral scene with dozens of mourners dressed in black surrounding an open grave under an overcast sky, painted in somber dark tones depicting a provincial burial ceremony"},
    {"title": "The Horse Fair", "artist": "Rosa Bonheur", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Rosa_Bonheur_-_The_Horse_Fair_-_Google_Art_Project.jpg/800px-Rosa_Bonheur_-_The_Horse_Fair_-_Google_Art_Project.jpg", "description": "Dynamic outdoor scene of powerful horses being paraded and traded at a market with handlers, featuring rich browns, grays, and natural colors with detailed anatomical rendering"},
    {"title": "The Third-Class Carriage", "artist": "Honoré Daumier", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Honoré_Daumier_-_The_Third-Class_Carriage_-_Google_Art_Project.jpg/800px-Honoré_Daumier_-_The_Third-Class_Carriage_-_Google_Art_Project.jpg", "description": "Interior of a crowded train carriage with working-class passengers including a nursing mother, painted in dark browns and muted tones capturing the cramped conditions of lower-class travel"},
    {"title": "The Agnew Clinic", "artist": "Thomas Eakins", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/The_Agnew_Clinic_1889_Thomas_Eakins.jpg/800px-The_Agnew_Clinic_1889_Thomas_Eakins.jpg", "description": "Bright medical amphitheater scene showing a surgical demonstration with doctors in white coats and observing students, painted in realistic detail with clinical whites and flesh tones"},
    {"title": "Nighthawks", "artist": "Edward Hopper", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/800px-Nighthawks_by_Edward_Hopper_1942.jpg", "description": "Urban night scene of an illuminated corner diner with isolated customers visible through large windows, featuring stark contrasts between warm yellow interior light and cool dark blue night exterior"},
    {"title": "Christina's World", "artist": "Andrew Wyeth", "style": "realism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Andrew_Wyeth_-_Christina%27s_World_-_Google_Art_Project.jpg/800px-Andrew_Wyeth_-_Christina%27s_World_-_Google_Art_Project.jpg", "description": "Rural landscape with a woman in a pink dress crawling through a vast dry grass field toward distant farm buildings under a pale sky, painted in muted pinks, browns, and grays"},
    
    # Impressionism
    {"title": "Impression, Sunrise", "artist": "Claude Monet", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/800px-Monet_-_Impression%2C_Sunrise.jpg", "description": "Harbor seascape at dawn with small boats silhouetted against orange sun reflecting on water, painted with loose brushstrokes in blue, orange, and gray tones capturing atmospheric light effects"},
    {"title": "Water Lilies", "artist": "Claude Monet", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/800px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg", "description": "Tranquil pond surface covered with pink and white water lilies floating among green lily pads with reflections of sky and foliage, painted with soft impressionistic brushwork in blues, greens, and pinks"},
    {"title": "The Starry Night", "artist": "Vincent van Gogh", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/800px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", "description": "Night sky landscape with swirling stars and crescent moon above a village with dark cypress tree in foreground, painted in bold blues, yellows, and swirling patterns with expressive brushstrokes"},
    {"title": "A Sunday on La Grande Jatte", "artist": "Georges Seurat", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/800px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg", "description": "Park landscape with elegantly dressed people relaxing by a river on a sunny day, painted with pointillist technique using small dots of color in greens, blues, and warm tones"},
    {"title": "Dance at Le Moulin de la Galette", "artist": "Pierre-Auguste Renoir", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Auguste_Renoir_-_Dance_at_Le_Moulin_de_la_Galette_-_Google_Art_Project.jpg/800px-Auguste_Renoir_-_Dance_at_Le_Moulin_de_la_Galette_-_Google_Art_Project.jpg", "description": "Lively outdoor dance scene with couples dancing and socializing under dappled sunlight filtering through trees, painted with warm colors and soft brushwork capturing joyful atmosphere"},
    {"title": "The Luncheon of the Boating Party", "artist": "Pierre-Auguste Renoir", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Pierre-Auguste_Renoir%2C_Le_déjeuner_des_canotiers.jpg/800px-Pierre-Auguste_Renoir%2C_Le_déjeuner_des_canotiers.jpg", "description": "Festive outdoor terrace scene with people dining and socializing after boating, featuring bright sunlight, colorful clothing, and warm social atmosphere painted with impressionistic light effects"},
    {"title": "Woman with a Parasol", "artist": "Claude Monet", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg/600px-Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg", "description": "Outdoor portrait of woman in white dress holding parasol standing on grassy hillside against cloudy blue sky, painted with loose brushstrokes capturing wind movement and natural light"},
    {"title": "The Absinthe Drinker", "artist": "Edgar Degas", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Edgar_Degas_-_In_a_Café_-_Google_Art_Project_2.jpg/600px-Edgar_Degas_-_In_a_Café_-_Google_Art_Project_2.jpg", "description": "Melancholic café interior showing isolated figures at a table with a glass of absinthe, painted in muted browns, greens, and yellows depicting urban alienation"},
    {"title": "Sunflowers", "artist": "Vincent van Gogh", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_Willem_van_Gogh_127.jpg/600px-Vincent_Willem_van_Gogh_127.jpg", "description": "Still life of vibrant yellow sunflowers in a vase against yellow background, painted with thick impasto brushstrokes and intense golden yellows with brown centers"},
    {"title": "Café Terrace at Night", "artist": "Vincent van Gogh", "style": "impressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_%28Yorck%29.jpg/600px-Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_%28Yorck%29.jpg", "description": "Nighttime urban scene of outdoor café with yellow-lit terrace and diners under awning beside cobblestone street under deep blue starry sky with expressive brushwork"},
    
    # Cubism
    {"title": "Les Demoiselles d'Avignon", "artist": "Pablo Picasso", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Pablo_Picasso%2C_1909-10%2C_Figure_dans_un_Fauteuil_%28Seated_Nude%2C_Femme_nue_assise%29%2C_oil_on_canvas%2C_92.1_x_73_cm%2C_Tate_Modern%2C_London.jpg/600px-Pablo_Picasso%2C_1909-10%2C_Figure_dans_un_Fauteuil_%28Seated_Nude%2C_Femme_nue_assise%29%2C_oil_on_canvas%2C_92.1_x_73_cm%2C_Tate_Modern%2C_London.jpg", "description": "Fragmented angular female figures with geometric faces showing multiple viewpoints simultaneously, painted in warm flesh tones, browns, and pinks with African mask influences"},
    {"title": "Guernica", "artist": "Pablo Picasso", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Mural_del_Gernika.jpg/800px-Mural_del_Gernika.jpg", "description": "Large monochromatic mural depicting war devastation with fragmented figures including screaming horse, bull, and human forms in anguished poses, painted in black, white, and gray tones"},
    {"title": "The Weeping Woman", "artist": "Pablo Picasso", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Pablo_Picasso%2C_1937%2C_Weeping_Woman_%28Femme_en_pleurs%29%2C_Tate_Modern.jpg/600px-Pablo_Picasso%2C_1937%2C_Weeping_Woman_%28Femme_en_pleurs%29%2C_Tate_Modern.jpg", "description": "Portrait of distressed woman crying with fractured face showing multiple angles simultaneously, painted in vivid colors including yellows, greens, reds, and blues with angular sharp forms"},
    {"title": "Violin and Candlestick", "artist": "Georges Braque", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Georges_Braque%2C_1910%2C_Violon_et_cruche_%28Violin_and_Pitcher%29%2C_oil_on_canvas%2C_117_x_73.5_cm%2C_Kunstmuseum_Basel.jpg/600px-Georges_Braque%2C_1910%2C_Violon_et_cruche_%28Violin_and_Pitcher%29%2C_oil_on_canvas%2C_117_x_73.5_cm%2C_Kunstmuseum_Basel.jpg", "description": "Fragmented still life with musical instrument deconstructed into geometric planes and multiple perspectives, painted in muted browns, tans, and grays in analytical cubist style"},
    {"title": "Three Musicians", "artist": "Pablo Picasso", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Pablo_Picasso%2C_1921%2C_Nous_autres_musiciens_%28Three_Musicians%29%2C_oil_on_canvas%2C_204_x_188_cm%2C_Philadelphia_Museum_of_Art.jpg/600px-Pablo_Picasso%2C_1921%2C_Nous_autres_musiciens_%28Three_Musicians%29%2C_oil_on_canvas%2C_204_x_188_cm%2C_Philadelphia_Museum_of_Art.jpg", "description": "Flat geometric figures of three musicians with instruments arranged in overlapping colorful shapes in browns, whites, blacks, yellows, and blues in synthetic cubist collage-like style"},
    {"title": "Girl with a Mandolin", "artist": "Pablo Picasso", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Pablo_Picasso%2C_1910%2C_Girl_with_a_Mandolin_%28Fanny_Tellier%29%2C_oil_on_canvas%2C_100.3_x_73.6_cm%2C_Museum_of_Modern_Art_New_York..jpg/600px-Pablo_Picasso%2C_1910%2C_Girl_with_a_Mandolin_%28Fanny_Tellier%29%2C_oil_on_canvas%2C_100.3_x_73.6_cm%2C_Museum_of_Modern_Art_New_York..jpg", "description": "Female figure with musical instrument fragmented into geometric planes showing multiple viewpoints, painted in subdued ochres, browns, and grays in analytical cubist approach"},
    {"title": "Houses at L'Estaque", "artist": "Georges Braque", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Georges_Braque%2C_1908%2C_Houses_at_L%27Estaque%2C_oil_on_canvas%2C_73_x_59.5_cm%2C_Kunstmuseum_Bern.jpg/600px-Georges_Braque%2C_1908%2C_Houses_at_L%27Estaque%2C_oil_on_canvas%2C_73_x_59.5_cm%2C_Kunstmuseum_Bern.jpg", "description": "Mediterranean landscape with cubic simplified houses and trees reduced to geometric forms, painted in earth tones of ochre, green, and brown showing early cubist style"},
    {"title": "Portrait of Ambroise Vollard", "artist": "Pablo Picasso", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Pablo_Picasso%2C_1910%2C_Portrait_of_Ambroise_Vollard%2C_oil_on_canvas%2C_92_x_65_cm%2C_Pushkin_Museum%2C_Moscow%2C_Russia.jpg/600px-Pablo_Picasso%2C_1910%2C_Portrait_of_Ambroise_Vollard%2C_oil_on_canvas%2C_92_x_65_cm%2C_Pushkin_Museum%2C_Moscow%2C_Russia.jpg", "description": "Fragmented portrait with face and body dissolved into intersecting geometric planes from multiple angles, painted in monochromatic browns and grays in analytical cubist technique"},
    {"title": "Man with a Guitar", "artist": "Georges Braque", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Georges_Braque%2C_1911-12%2C_Man_with_a_Guitar_%28Portrait_of_Pablo_Picasso%29%2C_oil_on_canvas%2C_130.2_x_72.9_cm%2C_Museum_of_Modern_Art%2C_New_York_..jpg/600px-Georges_Braque%2C_1911-12%2C_Man_with_a_Guitar_%28Portrait_of_Pablo_Picasso%29%2C_oil_on_canvas%2C_130.2_x_72.9_cm%2C_Museum_of_Modern_Art%2C_New_York_..jpg", "description": "Abstract figure with guitar broken into overlapping faceted planes and geometric shapes, painted in muted tans, browns, and grays showing analytical cubism's fragmentation"},
    {"title": "The Portuguese", "artist": "Georges Braque", "style": "cubism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Georges_Braque%2C_1911-12%2C_Le_Portugais_%28The_Emigrant%29%2C_oil_on_canvas%2C_117_x_81.5_cm%2C_Kunstmuseum_Basel%2C_Basel%2C_Switzerland.jpg/600px-Georges_Braque%2C_1911-12%2C_Le_Portugais_%28The_Emigrant%29%2C_oil_on_canvas%2C_117_x_81.5_cm%2C_Kunstmuseum_Basel%2C_Basel%2C_Switzerland.jpg", "description": "Musician figure fragmented into geometric shards with stenciled letters and numbers, painted in browns and grays combining analytical cubism with collage elements"},
    
    # Surrealism
    {"title": "The Persistence of Memory", "artist": "Salvador Dalí", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/The_Persistence_of_Memory.jpg/600px-The_Persistence_of_Memory.jpg", "description": "Dreamlike barren landscape with melting pocket watches draped over tree branch and abstract form under golden-orange cliffs by the sea, painted in realistic detail with surreal subject matter"},
    {"title": "The Son of Man", "artist": "René Magritte", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Magritte_TheSonOfMan.jpg/600px-Magritte_TheSonOfMan.jpg", "description": "Man in black suit and bowler hat with face obscured by floating green apple against seaside background, painted in realistic style with mysterious surreal juxtaposition"},
    {"title": "The Treachery of Images", "artist": "René Magritte", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/MagrittePipe.jpg/600px-MagrittePipe.jpg", "description": "Realistic painting of smoking pipe on plain background with text stating this is not a pipe, featuring browns and beiges questioning representation and reality"},
    {"title": "The Elephants", "artist": "Salvador Dalí", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Salvador_Dali_A_%28Dali_Atomicus%29_09633u.jpg/600px-Salvador_Dali_A_%28Dali_Atomicus%29_09633u.jpg", "description": "Surreal scene with elephants on impossibly long spindly legs walking through desert landscape, painted with meticulous realism in earth tones and blues creating dreamlike atmosphere"},
    {"title": "The Burning Giraffe", "artist": "Salvador Dalí", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Salvador_Dal%C3%AD_-_Giraffe_on_Fire.jpg/600px-Salvador_Dal%C3%AD_-_Giraffe_on_Fire.jpg", "description": "Nightmarish desert scene with distorted female figures supported by crutches and burning giraffe in background, painted in vivid reds, oranges, blues, and flesh tones with symbolic imagery"},
    {"title": "Swans Reflecting Elephants", "artist": "Salvador Dalí", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Salvador_Dali_NYWTS.jpg/600px-Salvador_Dali_NYWTS.jpg", "description": "Lake landscape where swan reflections transform into elephants through double-image technique, painted with realistic detail in natural colors creating optical illusion"},
    {"title": "The False Mirror", "artist": "René Magritte", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Magritte_TheFalseMirror.jpg/600px-Magritte_TheFalseMirror.jpg", "description": "Giant human eye with blue sky and white clouds reflected in iris and black pupil center, painted realistically exploring themes of perception and reality"},
    {"title": "The Lovers", "artist": "René Magritte", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Magritte_TheLover.jpg/600px-Magritte_TheLover.jpg", "description": "Two figures kissing with heads covered in white cloth obscuring faces, painted in muted colors exploring themes of hidden identity and blind love"},
    {"title": "Time Transfixed", "artist": "René Magritte", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/La_Dur%C3%A9e_poignard%C3%A9e.jpg/600px-La_Dur%C3%A9e_poignard%C3%A9e.jpg", "description": "Domestic interior with miniature steam locomotive emerging from fireplace with realistic detail, painted in browns, blacks, and warm tones creating impossible juxtaposition"},
    {"title": "The Metamorphosis of Narcissus", "artist": "Salvador Dalí", "style": "surrealism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Salvador_Dali%2C_Metamorphosis_of_Narcissus%2C_1937%2C_oil_on_canvas%2C_51.1_cm_%C3%97_78.1_cm_%2820.1_in_%C3%97_30.7_in%29%2C_Tate_Modern%2C_London.jpg/800px-Salvador_Dali%2C_Metamorphosis_of_Narcissus%2C_1937%2C_oil_on_canvas%2C_51.1_cm_%C3%97_78.1_cm_%2820.1_in_%C3%97_30.7_in%29%2C_Tate_Modern%2C_London.jpg", "description": "Mythological landscape with figure transforming into hand holding egg, painted in yellows, blues, and earth tones with precise double-image technique and symbolic metamorphosis"},
    
    # Renaissance
    {"title": "Mona Lisa", "artist": "Leonardo da Vinci", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/600px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg", "description": "Portrait of woman with enigmatic smile seated against distant landscape background, painted with sfumato technique in warm browns, greens, and muted colors with atmospheric perspective"},
    {"title": "The Last Supper", "artist": "Leonardo da Vinci", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%C3%9Altima_Cena_-_Da_Vinci_5.jpg/800px-%C3%9Altima_Cena_-_Da_Vinci_5.jpg", "description": "Biblical interior scene showing Jesus and twelve apostles at long table during last supper, painted with linear perspective in earth tones, reds, and blues with architectural setting"},
    {"title": "The Creation of Adam", "artist": "Michelangelo", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/800px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg", "description": "Fresco showing God reaching out to touch Adam's finger against blue sky, painted with muscular idealized figures in flesh tones, blues, and warm colors depicting moment of creation"},
    {"title": "The Birth of Venus", "artist": "Sandro Botticelli", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/800px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg", "description": "Mythological seascape with nude Venus standing on shell blown by wind gods toward shore with nymph offering cloak, painted in soft pastels, pinks, blues, and golds with flowing linear grace"},
    {"title": "The School of Athens", "artist": "Raphael", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/800px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg", "description": "Grand architectural interior with ancient philosophers gathered in classical building with arches, painted with perfect perspective in warm earth tones, reds, blues, and golds depicting intellectual gathering"},
    {"title": "Primavera", "artist": "Sandro Botticelli", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Botticelli-primavera.jpg/800px-Botticelli-primavera.jpg", "description": "Mythological garden scene with Venus, Mercury, and Three Graces among orange trees and flowers, painted in delicate colors with flowing drapery and decorative botanical details depicting spring"},
    {"title": "The Sistine Madonna", "artist": "Raphael", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Raphael_-_Sistine_Madonna_-_WGA18595.jpg/600px-Raphael_-_Sistine_Madonna_-_WGA18595.jpg", "description": "Religious scene of Madonna holding infant Jesus floating on clouds with cherubs below, painted in rich reds, blues, and golds with idealized figures and serene composition"},
    {"title": "David", "artist": "Michelangelo", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Michelangelo%27s_David_-_right_view_2.jpg/600px-Michelangelo%27s_David_-_right_view_2.jpg", "description": "Marble sculpture of nude male biblical hero in contrapposto pose showing idealized muscular anatomy, carved from white stone with classical proportions and naturalistic details"},
    {"title": "Vitruvian Man", "artist": "Leonardo da Vinci", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Da_Vinci_Vitruve_Luc_Viatour.jpg/600px-Da_Vinci_Vitruve_Luc_Viatour.jpg", "description": "Anatomical drawing of nude male figure with arms and legs extended in two positions inscribed in circle and square, rendered in ink on aged paper showing mathematical proportions"},
    {"title": "The Arnolfini Portrait", "artist": "Jan van Eyck", "style": "renaissance", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/600px-Van_Eyck_-_Arnolfini_Portrait.jpg", "description": "Domestic interior portrait of wealthy couple in elaborate clothing with dog, painted with meticulous detail in rich greens, browns, and reds using oil technique with symbolic objects"},
    
    # Baroque
    {"title": "The Night Watch", "artist": "Rembrandt", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/800px-The_Night_Watch_-_HD.jpg", "description": "Group portrait of militia company in dramatic lighting with captain in black and lieutenant in yellow prominent in center, painted with dynamic composition in rich browns, golds, and reds with chiaroscuro"},
    {"title": "Girl with a Pearl Earring", "artist": "Johannes Vermeer", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/600px-1665_Girl_with_a_Pearl_Earring.jpg", "description": "Portrait of young woman turning to viewer wearing exotic turban and large pearl earring against dark background, painted with soft lighting in blues, yellows, and flesh tones"},
    {"title": "The Calling of Saint Matthew", "artist": "Caravaggio", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/The_Calling_of_Saint_Matthew-Caravaggo_%281599-1600%29.jpg/800px-The_Calling_of_Saint_Matthew-Caravaggo_%281599-1600%29.jpg", "description": "Biblical interior scene with Christ pointing at tax collector Matthew at table illuminated by dramatic shaft of light, painted with tenebrism in dark browns with bright highlights"},
    {"title": "Las Meninas", "artist": "Diego Velázquez", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Las_Meninas_01.jpg/800px-Las_Meninas_01.jpg", "description": "Complex palace interior with young princess surrounded by attendants and artist at easel with mirror reflection of royal couple, painted with spatial depth in grays, pinks, reds, and whites"},
    {"title": "The Anatomy Lesson of Dr. Nicolaes Tulp", "artist": "Rembrandt", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg/800px-Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg", "description": "Medical demonstration scene with doctor showing arm anatomy to group of observers around corpse, painted with dramatic lighting in blacks, whites, and flesh tones with precise detail"},
    {"title": "The Milkmaid", "artist": "Johannes Vermeer", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg/600px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg", "description": "Domestic interior with servant pouring milk from pitcher in soft daylight, painted with meticulous detail in blues, yellows, and warm earth tones with luminous quality"},
    {"title": "Judith Slaying Holofernes", "artist": "Artemisia Gentileschi", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Artemisia_Gentileschi_-_Giuditta_decapita_Oloferne_-_Google_Art_Project.jpg/600px-Artemisia_Gentileschi_-_Giuditta_decapita_Oloferne_-_Google_Art_Project.jpg", "description": "Violent biblical scene with woman beheading general assisted by servant, painted with dramatic action and strong chiaroscuro in reds, golds, and dark shadows showing intense emotion"},
    {"title": "The Cardsharps", "artist": "Caravaggio", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Caravaggio_-_I_Bari.jpg/800px-Caravaggio_-_I_Bari.jpg", "description": "Genre scene of card players cheating young nobleman with dramatic lighting revealing deception, painted in earth tones with strong light-dark contrasts and psychological tension"},
    {"title": "View of Delft", "artist": "Johannes Vermeer", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vermeer-view-of-delft.jpg/800px-Vermeer-view-of-delft.jpg", "description": "Cityscape showing town reflected in canal under cloudy sky with dramatic light effects, painted with precise architectural detail in blues, grays, reds, and yellows with atmospheric perspective"},
    {"title": "The Storm on the Sea of Galilee", "artist": "Rembrandt", "style": "baroque", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg/600px-Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg", "description": "Dramatic seascape with boat full of disciples struggling in violent storm with tilted mast and churning waves, painted with dynamic diagonals in dark greens, browns, and dramatic highlights"},
    
    # Romanticism
    {"title": "The Third of May 1808", "artist": "Francisco Goya", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg/800px-El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg", "description": "Dramatic night scene of Spanish civilians being executed by firing squad with central figure in white shirt with arms raised, painted with emotional intensity in dark browns, blacks, reds, and stark white highlighting tragedy"},
    {"title": "Liberty Leading the People", "artist": "Eugène Delacroix", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eugène_Delacroix_-_Le_28_Juillet._La_Liberté_guidant_le_peuple.jpg/800px-Eugène_Delacroix_-_Le_28_Juillet._La_Liberté_guidant_le_peuple.jpg", "description": "Revolutionary scene with allegorical woman holding tricolor flag leading armed citizens over barricade with smoke and bodies, painted with dramatic action in reds, blues, and yellows with emotional heroism"},
    {"title": "The Raft of the Medusa", "artist": "Théodore Géricault", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_THÉODORE_GÉRICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/800px-JEAN_LOUIS_THÉODORE_GÉRICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg", "description": "Dramatic seascape with shipwreck survivors on makeshift raft waving at distant ship under stormy sky, painted with powerful muscular figures in browns, grays, and flesh tones showing human suffering"},
    {"title": "Wanderer above the Sea of Fog", "artist": "Caspar David Friedrich", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/600px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg", "description": "Solitary man in dark coat standing on rocky peak gazing at mountain landscape shrouded in mist, painted with atmospheric blues, grays, and greens evoking sublime contemplation of nature"},
    {"title": "The Hay Wain", "artist": "John Constable", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/John_Constable_The_Hay_Wain.jpg/800px-John_Constable_The_Hay_Wain.jpg", "description": "Idyllic rural landscape with horse-drawn cart crossing stream near cottage under cloudy sky, painted with naturalistic greens, blues, and earth tones celebrating pastoral English countryside"},
    {"title": "Saturn Devouring His Son", "artist": "Francisco Goya", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/600px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg", "description": "Horrific mythological scene of giant figure consuming human body against black background, painted with nightmarish intensity in dark browns, reds, and flesh tones depicting primal violence"},
    {"title": "The Fighting Temeraire", "artist": "J.M.W. Turner", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/The_Fighting_Temeraire%2C_JMW_Turner%2C_National_Gallery.jpg/800px-The_Fighting_Temeraire%2C_JMW_Turner%2C_National_Gallery.jpg", "description": "Maritime sunset scene with old warship being towed by steamboat under glowing sky with dramatic clouds, painted with luminous oranges, yellows, blues, and atmospheric light effects"},
    {"title": "The Death of Sardanapalus", "artist": "Eugène Delacroix", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Eugène_Ferdinand_Victor_Delacroix_-_La_Mort_de_Sardanapale.jpg/800px-Eugène_Ferdinand_Victor_Delacroix_-_La_Mort_de_Sardanapale.jpg", "description": "Chaotic scene of oriental king watching destruction of possessions and concubines from bed, painted with violent movement and rich reds, golds, flesh tones, and dramatic lighting showing decadent tragedy"},
    {"title": "The Nightmare", "artist": "Henry Fuseli", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/John_Henry_Fuseli_-_The_Nightmare.JPG/600px-John_Henry_Fuseli_-_The_Nightmare.JPG", "description": "Supernatural bedroom scene with sleeping woman in white draped across bed with demon sitting on chest and ghostly horse emerging from darkness, painted in dramatic reds, whites, and blacks evoking gothic horror"},
    {"title": "The Oxbow", "artist": "Thomas Cole", "style": "romanticism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Cole_Thomas_The_Oxbow_%28The_Connecticut_River_near_Northampton_1836%29.jpg/800px-Cole_Thomas_The_Oxbow_%28The_Connecticut_River_near_Northampton_1836%29.jpg", "description": "Panoramic landscape showing contrast between wild storm on left and pastoral cultivated valley on right with river bend, painted in greens, blues, and warm tones depicting American wilderness"},
    
    # Expressionism
    {"title": "The Scream", "artist": "Edvard Munch", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/600px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg", "description": "Anguished figure with hands to face on bridge under swirling red-orange sky with undulating landscape, painted with distorted forms in vivid reds, oranges, yellows, and blues expressing existential anxiety"},
    {"title": "The Kiss", "artist": "Gustav Klimt", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Gustav_Klimt_016.jpg/600px-Gustav_Klimt_016.jpg", "description": "Embracing couple wrapped in elaborate golden robes decorated with geometric patterns against flower meadow, painted with gold leaf and rich colors including yellows, golds, greens, and ornamental details"},
    {"title": "Portrait of Adele Bloch-Bauer I", "artist": "Gustav Klimt", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Gustav_Klimt_046.jpg/600px-Gustav_Klimt_046.jpg", "description": "Portrait of elegant woman in elaborate golden dress with geometric and spiral patterns against decorative background, painted with gold leaf, yellows, and browns with Byzantine-inspired ornamentation"},
    {"title": "The Madonna", "artist": "Edvard Munch", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Edvard_Munch_-_Madonna_%281894-1895%29.jpg/600px-Edvard_Munch_-_Madonna_%281894-1895%29.jpg", "description": "Sensual nude woman with flowing dark hair and closed eyes against red background with halo effect, painted with expressive brushwork in flesh tones, reds, and blacks evoking spiritual and erotic themes"},
    {"title": "The Dance of Life", "artist": "Edvard Munch", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Edvard_Munch_-_Dance_of_Life_%281899-1900%29.jpg/800px-Edvard_Munch_-_Dance_of_Life_%281899-1900%29.jpg", "description": "Beach scene with dancing couples including woman in white, red, and black dresses representing life stages, painted with flowing forms in reds, whites, blacks, and blues depicting human relationships"},
    {"title": "Street, Berlin", "artist": "Ernst Ludwig Kirchner", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Ernst_Ludwig_Kirchner_-_Berliner_Stra%C3%9Fenszene_-_Google_Art_Project.jpg/600px-Ernst_Ludwig_Kirchner_-_Berliner_Stra%C3%9Fenszene_-_Google_Art_Project.jpg", "description": "Urban street scene with elongated fashionable women and men in angular distorted forms, painted with sharp colors including pinks, greens, blues, and blacks showing modern city alienation"},
    {"title": "Self-Portrait with Chinese Lantern Plant", "artist": "Egon Schiele", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Egon_Schiele_-_Selbstbildnis_mit_Lampionfrüchten_-_1912.jpeg/600px-Egon_Schiele_-_Selbstbildnis_mit_Lampionfrüchten_-_1912.jpeg", "description": "Intense self-portrait with gaunt angular face and twisted pose holding orange plant against dark background, painted with harsh contours in browns, oranges, and flesh tones with psychological intensity"},
    {"title": "The Blue Rider", "artist": "Wassily Kandinsky", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Vassily_Kandinsky%2C_1903_-_Der_Blaue_Reiter.jpg/600px-Vassily_Kandinsky%2C_1903_-_Der_Blaue_Reiter.jpg", "description": "Rider on blue horse galloping through landscape with simplified forms, painted with bold blues, greens, and whites with expressive brushwork showing movement toward abstraction"},
    {"title": "Large Blue Horses", "artist": "Franz Marc", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Franz_Marc-The_Large_Blue_Horses-1911.jpg/800px-Franz_Marc-The_Large_Blue_Horses-1911.jpg", "description": "Three bright blue horses with curved necks in rolling landscape, painted with bold unnatural colors including blues, reds, yellows, and greens expressing spiritual connection with nature"},
    {"title": "Tower of Blue Horses", "artist": "Franz Marc", "style": "expressionism", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Franz_Marc_-_Tirol.jpg/600px-Franz_Marc_-_Tirol.jpg", "description": "Mountain landscape with geometric forms and bold colors in blues, greens, and earth tones showing stylized Tyrolean countryside with expressive color symbolism"},
    
    # Pop Art
    {"title": "Campbell's Soup Cans", "artist": "Andy Warhol", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Andy_Warhol_Campbell%27s_Soup_Can_1964_%28ceramic%29.jpg/600px-Andy_Warhol_Campbell%27s_Soup_Can_1964_%28ceramic%29.jpg", "description": "Mass-produced consumer product rendered as art with red and white soup can labels presented in grid format, painted with flat colors and commercial graphics elevating everyday object"},
    {"title": "Marilyn Diptych", "artist": "Andy Warhol", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Andy_Warhol_Marilyn_1967.jpg/600px-Andy_Warhol_Marilyn_1967.jpg", "description": "Repeated silkscreen portrait of Marilyn Monroe in bright pink, yellow, blue, and green with high contrast and commercial printing aesthetic celebrating celebrity culture"},
    {"title": "Whaam!", "artist": "Roy Lichtenstein", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Roy_Lichtenstein_Whaam.jpg/800px-Roy_Lichtenstein_Whaam.jpg", "description": "Comic book style war scene with fighter jet firing missile with explosion and bold text, painted with Ben-Day dots in primary reds, yellows, and blues mimicking printed comics"},
    {"title": "Drowning Girl", "artist": "Roy Lichtenstein", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Drowning_Girl.jpg/600px-Drowning_Girl.jpg", "description": "Woman's face in water with thought bubble text in comic book style, painted with Ben-Day dots in blues and flesh tones with thick black outlines depicting melodramatic romance"},
    {"title": "Just What Is It That Makes Today's Homes So Different, So Appealing?", "artist": "Richard Hamilton", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Hamilton-appealing2.jpg/600px-Hamilton-appealing2.jpg", "description": "Collage interior with bodybuilder and pin-up surrounded by consumer products and advertisements, assembled from magazine clippings in vibrant colors critiquing consumer culture"},
    {"title": "I Was a Rich Man's Plaything", "artist": "Eduardo Paolozzi", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Bunk_I_was_a_Rich_Man%27s_Plaything.jpg/600px-Bunk_I_was_a_Rich_Man%27s_Plaything.jpg", "description": "Early pop art collage with pin-up girl, Coca-Cola logo, fighter plane and text fragments from magazines, assembled in reds, blues, and blacks exploring mass media imagery"},
    {"title": "Flag", "artist": "Jasper Johns", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Jasper_Johns_-_Flag_-_Google_Art_Project.jpg/800px-Jasper_Johns_-_Flag_-_Google_Art_Project.jpg", "description": "American flag rendered with encaustic and collage technique with textured surface, painted in red, white, and blue transforming patriotic symbol into abstract painterly object"},
    {"title": "Target with Four Faces", "artist": "Jasper Johns", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Jasper_Johns_-_Target_with_Plaster_Casts_-_Google_Art_Project.jpg/600px-Jasper_Johns_-_Target_with_Plaster_Casts_-_Google_Art_Project.jpg", "description": "Concentric circles target in red, yellow, and blue with plaster cast faces above in compartments, combining painting and sculpture with everyday imagery"},
    {"title": "Eight Elvises", "artist": "Andy Warhol", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Andy_Warhol_-_Elvis_-_1962-63.jpg/600px-Andy_Warhol_-_Elvis_-_1962-63.jpg", "description": "Repeated silkscreen images of Elvis Presley as cowboy in silver and black creating rhythmic pattern, exploring celebrity, repetition, and mass production"},
    {"title": "Green Coca-Cola Bottles", "artist": "Andy Warhol", "style": "pop art", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Andy_Warhol_-_Coca-Cola_%283%29_-_1962.jpg/600px-Andy_Warhol_-_Coca-Cola_%283%29_-_1962.jpg", "description": "Grid of repeated Coca-Cola bottles in black and white showing mass-produced consumer product as art subject, painted with silkscreen technique emphasizing uniformity and commercialism"},
]


def generate_painting_embedding(painting):
    """Generate embedding for a painting using text description"""
    try:
        # Create a comprehensive text prompt from painting attributes
        text_prompt = f"{painting['title']} by {painting['artist']}, {painting['style']} painting. {painting['description']}"
        
        print(f"  Generating embedding from description: {text_prompt[:100]}...")
        embedding = get_text_embedding(text_prompt)
        return embedding
    except Exception as e:
        raise Exception(f"Failed to generate embedding for {painting['title']}: {str(e)}")


def populate_database():
    """Populate the database with paintings and their embeddings"""
    db = SessionLocal()
    
    try:
        print(f"Starting to populate database with {len(PAINTINGS)} paintings...")
        
        # Check if paintings already exist
        check_query = text("SELECT COUNT(*) FROM paintings")
        result = db.execute(check_query)
        count = result.scalar()
        
        if count > 0:
            print(f"\nDatabase already contains {count} paintings.")
            response = input("Do you want to clear and repopulate? (yes/no): ")
            if response.lower() != 'yes':
                print("Skipping population.")
                return
            
            # Clear existing paintings
            delete_query = text("DELETE FROM paintings")
            db.execute(delete_query)
            db.commit()
            print("Cleared existing paintings.")
        
        # Insert paintings with embeddings
        insert_query = text("""
            INSERT INTO paintings (title, artist, image_url, style, embedding)
            VALUES (:title, :artist, :image_url, :style, :embedding)
        """)
        
        success_count = 0
        for i, painting in enumerate(PAINTINGS, 1):
            try:
                print(f"Processing {i}/{len(PAINTINGS)}: {painting['title']} by {painting['artist']}...")
                
                # Generate embedding
                embedding = generate_painting_embedding(painting)
                
                # Insert into database
                db.execute(insert_query, {
                    "title": painting["title"],
                    "artist": painting["artist"],
                    "image_url": painting["image_url"],
                    "style": painting["style"],
                    "embedding": embedding
                })
                
                success_count += 1
                
                # Commit every 10 paintings to avoid losing progress
                if i % 10 == 0:
                    db.commit()
                    print(f"  ✓ Committed {i} paintings")
                
            except Exception as e:
                print(f"  ✗ Error processing {painting['title']}: {str(e)}")
                continue
        
        # Final commit
        db.commit()
        
        print(f"\n{'='*60}")
        print(f"Successfully populated {success_count}/{len(PAINTINGS)} paintings!")
        print(f"{'='*60}")
        
        # Verify the insertion
        verify_query = text("SELECT COUNT(*) FROM paintings")
        result = db.execute(verify_query)
        final_count = result.scalar()
        print(f"\nTotal paintings in database: {final_count}")
        
        # Show sample of inserted paintings
        sample_query = text("""
            SELECT title, artist, style 
            FROM paintings 
            ORDER BY created_at DESC 
            LIMIT 5
        """)
        samples = db.execute(sample_query).fetchall()
        
        print("\nSample of inserted paintings:")
        for sample in samples:
            print(f"  - {sample.title} by {sample.artist} ({sample.style})")
        
    except Exception as e:
        print(f"\n✗ Error during population: {str(e)}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    print("="*60)
    print("Art Recommendation System - Database Population")
    print("="*60)
    print("\nThis script will populate the database with 100+ famous paintings")
    print("and generate embeddings for each one using CLIP.\n")
    
    try:
        populate_database()
        print("\n✓ Database population completed successfully!")
    except KeyboardInterrupt:
        print("\n\nOperation cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Failed to populate database: {str(e)}")
        sys.exit(1)
